# 설정파일
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contact
    username: root
    password: kurtcobain99
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

  freemarker:
    cache: false

logging:
  level:
    # logger에서 SQL을 보기 위해 -> show_sql은 system.out으로 뜨기 때문에 주석으로 빼줬다.
    org.hibernate.sql: debug
    org.hibernate.type: trace

server:
  port: 8080